####################################################
# LSrouter.py
# Name:
# HUID:
#####################################################

from json import dumps, loads
from heapq import heappop, heappush
from itertools import count

from packet import Packet
from router import Router


class LSrouter(Router):
    """Link state routing protocol implementation.

    Add your own class fields and initialization code (e.g. to create forwarding table
    data structures). See the `Router` base class for docstrings of the methods to
    override.
    """

    def __init__(self, addr, heartbeat_time):
        Router.__init__(self, addr)  # Initialize base class - DO NOT REMOVE
        self.heartbeat_time = heartbeat_time
        self.last_time = 0
        self.neighbors = {}
        self.link_state = {self.addr: {}}
        self.sequence_numbers = {self.addr: 0}
        self.sequence_number = 0
        self.forwarding_table = {}

    def _port_for_neighbor(self, endpoint):
        if endpoint in self.neighbors:
            value = self.neighbors[endpoint]
            return value[0] if isinstance(value, (tuple, list)) else value
        for port, value in self.neighbors.items():
            if isinstance(value, (tuple, list)) and value and value[0] == endpoint:
                return port
        return None

    def _neighbor_ports(self):
        for key, value in self.neighbors.items():
            if isinstance(value, (tuple, list)) and len(value) >= 2 and value[0] != key:
                if isinstance(key, int):
                    yield key
                else:
                    yield value[0]
            elif isinstance(key, int):
                yield key
            else:
                yield value

    def handle_packet(self, port, packet):
        """Process incoming packet."""
        if packet.is_traceroute:
            # Hint: this is a normal data packet
            # If the forwarding table contains packet.dst_addr
            #   send packet based on forwarding table, e.g., self.send(port, packet)
            next_port = self.forwarding_table.get(packet.dst_addr)
            if next_port is not None:
                self.send(next_port, packet)
        else:
            # Hint: this is a routing packet generated by your routing protocol
            # If the sequence number is higher and the received link state is different
            #   update the local copy of the link state
            #   update the forwarding table
            #   broadcast the packet to other neighbors
            try:
                state = loads(packet.content)
                origin = state["addr"]
                sequence_number = state["sequence_number"]
                links = state["links"]
            except Exception:
                return

            if sequence_number <= self.sequence_numbers.get(origin, -1):
                return

            self.sequence_numbers[origin] = sequence_number
            self.link_state[origin] = links

            distances = {self.addr: 0}
            first_hops = {}
            push_order = count()
            heap = [(0, next(push_order), self.addr, None)]

            while heap:
                distance, _, node, first_hop = heappop(heap)
                if distance != distances.get(node):
                    continue
                for neighbor, cost in self.link_state.get(node, {}).items():
                    new_distance = distance + cost
                    if new_distance < distances.get(neighbor, float("inf")):
                        distances[neighbor] = new_distance
                        first_hops[neighbor] = neighbor if node == self.addr else first_hop
                        heappush(
                            heap,
                            (new_distance, next(push_order), neighbor, first_hops[neighbor]),
                        )

            self.forwarding_table = {
                destination: next_port
                for destination, first_hop in first_hops.items()
                for next_port in (self._port_for_neighbor(first_hop),)
                if next_port is not None
            }

            for neighbor_port in self._neighbor_ports():
                if neighbor_port != port:
                    self.send(neighbor_port, packet)

    def handle_new_link(self, port, endpoint, cost):
        """Handle new link."""
        self.neighbors[endpoint] = (port, cost)
        self.link_state[self.addr][endpoint] = cost
        self.sequence_number += 1
        self.sequence_numbers[self.addr] = self.sequence_number

        distances = {self.addr: 0}
        first_hops = {}
        push_order = count()
        heap = [(0, next(push_order), self.addr, None)]

        while heap:
            distance, _, node, first_hop = heappop(heap)
            if distance != distances.get(node):
                continue
            for neighbor, link_cost in self.link_state.get(node, {}).items():
                new_distance = distance + link_cost
                if new_distance < distances.get(neighbor, float("inf")):
                    distances[neighbor] = new_distance
                    first_hops[neighbor] = neighbor if node == self.addr else first_hop
                    heappush(
                        heap,
                        (new_distance, next(push_order), neighbor, first_hops[neighbor]),
                    )

        self.forwarding_table = {
            destination: next_port
            for destination, first_hop in first_hops.items()
            for next_port in (self._port_for_neighbor(first_hop),)
            if next_port is not None
        }

        packet = Packet(
            Packet.ROUTING,
            self.addr,
            None,
            dumps(
                {
                    "addr": self.addr,
                    "sequence_number": self.sequence_number,
                    "links": self.link_state[self.addr],
                }
            ),
        )
        for neighbor_port in self._neighbor_ports():
            self.send(neighbor_port, packet)

    def handle_remove_link(self, port):
        """Handle removed link."""
        removed_endpoint = None

        if port in self.neighbors:
            value = self.neighbors.pop(port)
            if isinstance(value, (tuple, list)):
                removed_endpoint = value[0]
        else:
            for endpoint, value in list(self.neighbors.items()):
                if isinstance(value, (tuple, list)) and value and value[0] == port:
                    removed_endpoint = endpoint
                    del self.neighbors[endpoint]
                    break

        if removed_endpoint is not None:
            self.link_state.setdefault(self.addr, {}).pop(removed_endpoint, None)

        self.sequence_number += 1
        self.sequence_numbers[self.addr] = self.sequence_number

        distances = {self.addr: 0}
        first_hops = {}
        heap = [(0, self.addr, None)]

        while heap:
            distance, node, first_hop = heappop(heap)
            if distance != distances.get(node):
                continue
            for neighbor, cost in self.link_state.get(node, {}).items():
                new_distance = distance + cost
                if new_distance < distances.get(neighbor, float("inf")):
                    distances[neighbor] = new_distance
                    first_hops[neighbor] = neighbor if node == self.addr else first_hop
                    heappush(heap, (new_distance, neighbor, first_hops[neighbor]))

        self.forwarding_table = {
            destination: next_port
            for destination, first_hop in first_hops.items()
            for next_port in (self._port_for_neighbor(first_hop),)
            if next_port is not None
        }

        packet = Packet(
            Packet.ROUTING,
            self.addr,
            None,
            dumps(
                {
                    "addr": self.addr,
                    "sequence_number": self.sequence_number,
                    "links": self.link_state[self.addr],
                }
            ),
        )
        for neighbor_port in self._neighbor_ports():
            self.send(neighbor_port, packet)

    def handle_time(self, time_ms):
        """Handle current time."""
        if time_ms - self.last_time >= self.heartbeat_time:
            self.last_time = time_ms
            packet = Packet(
                Packet.ROUTING,
                self.addr,
                None,
                dumps(
                    {
                        "addr": self.addr,
                        "sequence_number": self.sequence_number,
                        "links": self.link_state[self.addr],
                    }
                ),
            )
            for neighbor_port in self._neighbor_ports():
                self.send(neighbor_port, packet)

    def __repr__(self):
        """Representation for debugging in the network visualizer."""
        #   NOTE This method is for your own convenience and will not be graded
        return (
            f"LSrouter(addr={self.addr}, "
            f"neighbors={self.neighbors}, "
            f"forwarding_table={self.forwarding_table})"
        )
